/*
 * StartPannel: Display the menu for the user to select
 */

/*
 * StartPanel.java
 *
 */
package GUI;


import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author NTQuang
 */
public class Help extends javax.swing.JPanel {

  
    /**
     * Creates new form StartPanel
     */
    public Help() {
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGrWord = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(660, 550));
        setPreferredSize(new java.awt.Dimension(850, 590));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N
        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 590));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btGrWord;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
