/*
 * StartPannel: Display the menu for the user to select
 */

/*
 * StartPanel.java
 *
 */
package GUI;

import Entity.Word;
import Interaction.LessonInteraction;
import Interaction.WordInteraction;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GiangNT
 */
public class Learn extends JPanel implements KeyListener {

    /**
     * Creates new form StartPanel
     */
    public Learn() {

        initComponents();
        pnLearn.addKeyListener(this);
        btNext.addKeyListener(this);
        btPrivious.addKeyListener(this);
        btStart.addKeyListener(this);

        tbAuto.addKeyListener(this);
        tbLesson.addKeyListener(this);
        tbWord.addKeyListener(this);


        // allow learn to process Key events
        fillTbLesson();
        tbWord.setGridColor(new java.awt.Color(204, 204, 204));
        tbWord.setSelectionBackground(new Color(199, 251, 111));
        tbWord.setSelectionForeground(new Color(0, 0, 0));
    }

    private void fillTbLesson() {
        Vector title = new Vector();
        title.add("ID");
        title.add("Lesson Name");
        Vector lesson = LessonInteraction.readLesson();
        if (lesson.size() >= 0) {
            tbLesson.setModel(new DefaultTableModel(lesson, title));
            tbLesson.getColumnModel().getColumn(1).setPreferredWidth(20);

            tbLesson.getColumn("ID").setWidth(0);
            tbLesson.getColumn("ID").setMinWidth(0);
            tbLesson.getColumn("ID").setMaxWidth(0);

            tbLesson.setDragEnabled(false);
        }
    }

    private void fillTbWord() {
        Vector title = new Vector();
        title.add("ID");
        title.add("Kanj");
        title.add("Furigana");
        title.add("Meaning");
        title.add("ImagePath");
        title.add("LessonID");
        Vector word = WordInteraction.readWordByLId(lessonId);
        if (word.size() >= 0) {
            tbWord.setModel(new DefaultTableModel(word, title));
            tbWord.getColumnModel().getColumn(1).setPreferredWidth(20);
            tbWord.getColumnModel().getColumn(2).setPreferredWidth(20);
            tbWord.getColumnModel().getColumn(3).setPreferredWidth(20);

            tbWord.getColumn("ID").setWidth(0);
            tbWord.getColumn("ID").setMinWidth(0);
            tbWord.getColumn("ID").setMaxWidth(0);
            tbWord.getColumn("ImagePath").setWidth(0);
            tbWord.getColumn("ImagePath").setMinWidth(0);
            tbWord.getColumn("ImagePath").setMaxWidth(0);
            tbWord.getColumn("LessonID").setWidth(0);
            tbWord.getColumn("LessonID").setMinWidth(0);
            tbWord.getColumn("LessonID").setMaxWidth(0);
            tbWord.setDragEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnLearn = new javax.swing.JPanel();
        lbImage = new javax.swing.JLabel();
        lbKanji = new javax.swing.JLabel();
        lbMeaning = new javax.swing.JLabel();
        lbFurigana = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btNext = new javax.swing.JButton();
        btPrivious = new javax.swing.JButton();
        tbAuto = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        btStart = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btQTest = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jSpLesson = new javax.swing.JScrollPane();
        tbLesson = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jsWord = new javax.swing.JScrollPane();
        tbWord = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(660, 550));
        setPreferredSize(new java.awt.Dimension(850, 590));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnLearn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnLearn.setName("pnLearn"); // NOI18N
        pnLearn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/welcome.png"))); // NOI18N
        lbImage.setName("lbImage"); // NOI18N
        pnLearn.add(lbImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 378, 160));

        lbKanji.setFont(lbKanji.getFont().deriveFont(lbKanji.getFont().getSize()+14f));
        lbKanji.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbKanji.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/select.png"))); // NOI18N
        lbKanji.setName("lbKanji"); // NOI18N
        pnLearn.add(lbKanji, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 169, 390, 50));

        lbMeaning.setFont(lbMeaning.getFont().deriveFont(lbMeaning.getFont().getSize()+9f));
        lbMeaning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMeaning.setName("lbMeaning"); // NOI18N
        pnLearn.add(lbMeaning, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 390, 60));

        lbFurigana.setFont(lbFurigana.getFont().deriveFont(lbFurigana.getFont().getSize()+9f));
        lbFurigana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFurigana.setName("lbFurigana"); // NOI18N
        pnLearn.add(lbFurigana, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 390, 50));

        jPanel1.add(pnLearn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 390, 330));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btNext.setText("Next");
        btNext.setEnabled(false);
        btNext.setName("btNext"); // NOI18N
        btNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNextActionPerformed(evt);
            }
        });
        jPanel5.add(btNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 40));

        btPrivious.setText("Previous");
        btPrivious.setEnabled(false);
        btPrivious.setName("btPrivious"); // NOI18N
        btPrivious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPriviousActionPerformed(evt);
            }
        });
        jPanel5.add(btPrivious, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 40));

        tbAuto.setText("Auto");
        tbAuto.setEnabled(false);
        tbAuto.setName("tbAuto"); // NOI18N
        tbAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbAutoActionPerformed(evt);
            }
        });
        jPanel5.add(tbAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 100, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 120, 330));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 570, 390));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btStart.setText("Start Study");
        btStart.setName("btStart"); // NOI18N
        btStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartActionPerformed(evt);
            }
        });
        jPanel2.add(btStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 110, 50));

        jLabel4.setText("Message: ");
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        btQTest.setText("Quiz test");
        btQTest.setName("btQTest"); // NOI18N
        jPanel2.add(btQTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 110, 50));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jSpLesson.setName("jSpLesson"); // NOI18N

        tbLesson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbLesson.setName("tbLesson"); // NOI18N
        tbLesson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLessonMouseClicked(evt);
            }
        });
        jSpLesson.setViewportView(tbLesson);

        jScrollPane1.setViewportView(jSpLesson);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 240, 270));

        jTextField1.setName("jTextField1"); // NOI18N
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 240, -1));

        jButton1.setText("Search");
        jButton1.setName("jButton1"); // NOI18N
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 280, 580));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Your leson is: ");
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jsWord.setName("jsWord"); // NOI18N

        tbWord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbWord.setName("tbWord"); // NOI18N
        tbWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbWordMouseClicked(evt);
            }
        });
        jsWord.setViewportView(tbWord);

        jScrollPane2.setViewportView(jsWord);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 520, 120));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 570, 190));
    }// </editor-fold>//GEN-END:initComponents

    private void btNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNextActionPerformed
        // TODO add your handling code here:
        try {
            row = tbWord.getSelectedRow() + 1;
            if (row < tbWord.getRowCount()) {
                tbWord.clearSelection();
                tbWord.changeSelection(row, 5, false, false);
                word = new Word();
                selection(word, row);
                fillLearn();
            }
        } catch (Exception e) {
            //System.out.println("Het tu r");
        }

    }//GEN-LAST:event_btNextActionPerformed

    private void btPriviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPriviousActionPerformed
        // TODO add your handling code here:
        try {
            row = tbWord.getSelectedRow() - 1;
            if (row > -1) {
                tbWord.clearSelection();
                tbWord.changeSelection(row, 5, false, false);
                word = new Word();
                selection(word, row);
                fillLearn();
            }
        } catch (Exception e) {
            //System.out.println("Het tu r");
        }
    }//GEN-LAST:event_btPriviousActionPerformed

    private void tbLessonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLessonMouseClicked
        // TODO add your handling code here:
        tbWord.setEnabled(false);
        if (tbLesson.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Please choose the lesson! :D");
            return;
        }
        row = tbLesson.getSelectedRow();
        lessonId = (Integer) tbLesson.getValueAt(row, 0);

        fillTbWord();
    }//GEN-LAST:event_tbLessonMouseClicked

    private void tbWordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbWordMouseClicked
        // TODO add your handling code here:
        if (tbWord.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Please choose the lesson :D");
            return;
        }
        row = tbWord.getSelectedRow();
        word = new Word();
        selection(word, row);
        fillLearn();
    }//GEN-LAST:event_tbWordMouseClicked

    private void btStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartActionPerformed
        // TODO add your handling code here:
        lbImage.setIcon(null);
        lbKanji.setIcon(null);

        //Enable BUTTONS
        btNext.setEnabled(true);
        btPrivious.setEnabled(true);
        tbAuto.setEnabled(true);

        pnLearn.setFocusable(true);
        pnLearn.requestFocusInWindow();
    }//GEN-LAST:event_btStartActionPerformed

    private void tbAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbAutoActionPerformed
        // TODO add your handling code here:
        if (tbAuto.isSelected()) {
            auto(true);
        } else {
            auto(false);
        }
    }//GEN-LAST:event_tbAutoActionPerformed
    //ham chon tu

    public int selection(Word w, int r) {
        w.setWordID((Integer) tbWord.getValueAt(r, 0));
        w.setKanji((String) tbWord.getValueAt(r, 1));
        w.setFurigana((String) tbWord.getValueAt(r, 2));
        w.setMeaning((String) tbWord.getValueAt(r, 3));
        w.setImage((String) tbWord.getValueAt(r, 4));
        w.setLessonID((Integer) tbWord.getValueAt(r, 5));

        return r;
    }

    private int fillLearn() {
        if (word.getImage() != null) {
            lbImage.setIcon(new ImageIcon(word.getImage()));
        }

        lbKanji.setText(word.getKanji());
        lbFurigana.setText(word.getFurigana());
        lbMeaning.setText(word.getMeaning());
        return 0;
    }
////

    private boolean NextWord(boolean a) {

        if (a == true) {
            try {
                row = tbWord.getSelectedRow() + 1;
                if (row < tbWord.getRowCount()) {
                    tbWord.clearSelection();
                    tbWord.changeSelection(row, 5, false, false);
                    word = new Word();
                    selection(word, row);
                    fillLearn();
                } else {
                    a = false;
                }
            } catch (Exception e) {
                //System.out.println("next word false");
            }
        }
        return a;
    }

///
    private boolean PreWord(boolean a) {

        if (a == false) {
            try {
                row = tbWord.getSelectedRow() - 1;
                if (row > -1) {
                    tbWord.clearSelection();
                    tbWord.changeSelection(row, 5, false, false);
                    word = new Word();
                    selection(word, row);
                    fillLearn();
                } else {
                    a = true;
                }
            } catch (Exception e) {
                //System.out.println("Preview word false");
            }
        }
        return a;
    }
    //ham auto

    public void auto(boolean a) {
        ActionListener action = new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                i += (Math.random() * 10);
                if (i >= 100) {
                    b = NextWord(b);
                    b = PreWord(b);
                    i = 0;
                }
            }
        };
        if (t == null) {
            t = new Timer(100, action);
        }
        if (a) {
            t.start();
        } else if (t.isRunning()) {
            t.stop();
        }


    }
    private int row = 0;
    private int lessonId = 0;
    private Word word = null;
    private int i = 0;
    private Timer t = null;
    private boolean b = true;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNext;
    private javax.swing.JButton btPrivious;
    private javax.swing.JButton btQTest;
    private javax.swing.JButton btStart;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jSpLesson;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JScrollPane jsWord;
    private javax.swing.JLabel lbFurigana;
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbKanji;
    private javax.swing.JLabel lbMeaning;
    private javax.swing.JPanel pnLearn;
    private javax.swing.JToggleButton tbAuto;
    private javax.swing.JTable tbLesson;
    private javax.swing.JTable tbWord;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
//        //System.out.println("bb");
    }

    @Override
    public void keyReleased(KeyEvent e) {
//        //System.out.println("haha");
    }

    @Override
    public void keyPressed(KeyEvent evt) {
        int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_LEFT) {
            PreWord(false);
        } else if (keyCode == KeyEvent.VK_RIGHT) {
            NextWord(true);
        } else if (keyCode == KeyEvent.VK_UP) {
            //System.out.println("up");
        } else if (keyCode == KeyEvent.VK_DOWN) {
            //System.out.println("dow");
        }
    }
}
