/*
 * StartPannel: Display the menu for the user to select
 */

/*
 * StartPanel.java
 *
 */
package GUI;

import Entity.Lesson;
import Entity.Word;
import Interaction.LessonInteraction;
import Interaction.WordInteraction;
import java.awt.Color;
import java.io.File;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Giang
 */
public class Library extends javax.swing.JPanel {

    /**
     * Creates new form StartPanel
     */
    public Library() {
        initComponents();
        fillTbLesson();
        tbWord.setGridColor(new java.awt.Color(204, 204, 204));
        tbWord.setSelectionBackground(new Color(199, 251, 111));
        tbWord.setSelectionForeground(new Color(0, 0, 0));
    }

    private void fillTbLesson() {
        Vector title = new Vector();
        title.add("ID");
        title.add("Lesson Name");
        Vector lesson = LessonInteraction.readLesson();
        if (lesson.size() >= 0) {
            tbLesson.setModel(new DefaultTableModel(lesson, title));
            tbLesson.getColumnModel().getColumn(1).setPreferredWidth(20);
            tbLesson.getColumn("ID").setWidth(0);
            tbLesson.getColumn("ID").setMinWidth(0);
            tbLesson.getColumn("ID").setMaxWidth(0);
            tbLesson.setDragEnabled(false);
        }
    }

    private void fillTbWord() {
        Vector title = new Vector();
        title.add("ID");
        title.add("Kanj");
        title.add("Furigana");
        title.add("Meaning");
        title.add("ImagePath");
        title.add("LessonID");

        Vector word = WordInteraction.readWordByLId(lessonId);
        if (word.size() >= 0) {
            tbWord.setModel(new DefaultTableModel(word, title));
            tbWord.getColumnModel().getColumn(1).setPreferredWidth(20);
            tbWord.getColumnModel().getColumn(2).setPreferredWidth(20);
            tbWord.getColumnModel().getColumn(3).setPreferredWidth(20);

            tbWord.getColumn("ID").setWidth(0);
            tbWord.getColumn("ID").setMinWidth(0);
            tbWord.getColumn("ID").setMaxWidth(0);
            tbWord.getColumn("ImagePath").setWidth(0);
            tbWord.getColumn("ImagePath").setMinWidth(0);
            tbWord.getColumn("ImagePath").setMaxWidth(0);
            tbWord.getColumn("LessonID").setWidth(0);
            tbWord.getColumn("LessonID").setMinWidth(0);
            tbWord.getColumn("LessonID").setMaxWidth(0);
            tbWord.setDragEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btNewLibrary = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbWord = new javax.swing.JTable();
        btDeleteWordLibrary = new javax.swing.JButton();
        btUpdateWordLibrary = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btAddLessonLibrary = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jSpLesson = new javax.swing.JScrollPane();
        tbLesson = new javax.swing.JTable();
        btDeleteLessonLibrary = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbImagePreviewLibrary = new javax.swing.JLabel();
        lbFuriganaLibrary = new javax.swing.JLabel();
        lbMeaningPreviewLibrary = new javax.swing.JLabel();
        lbKanjPreviewLibrary = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfImageLibrary = new javax.swing.JTextField();
        btUpdateLibrary = new javax.swing.JButton();
        btBrowserImageLibrary = new javax.swing.JButton();
        tfMeaningLibrary = new javax.swing.JTextField();
        tfFuriganaLibrary = new javax.swing.JTextField();
        tfKanjiLibrary = new javax.swing.JTextField();
        btSaveLibrary = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(660, 550));
        setPreferredSize(new java.awt.Dimension(850, 590));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btNewLibrary.setText("New");
        btNewLibrary.setEnabled(false);
        btNewLibrary.setName("btNewLibrary"); // NOI18N
        btNewLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewLibraryActionPerformed(evt);
            }
        });
        jPanel1.add(btNewLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 80, -1));

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tbWord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbWord.setName("tbWord"); // NOI18N
        tbWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbWordMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbWord);

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 500, 250));

        btDeleteWordLibrary.setText("Delete Word");
        btDeleteWordLibrary.setEnabled(false);
        btDeleteWordLibrary.setName("btDeleteWordLibrary"); // NOI18N
        btDeleteWordLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteWordLibraryActionPerformed(evt);
            }
        });
        jPanel1.add(btDeleteWordLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        btUpdateWordLibrary.setText("Update Word");
        btUpdateWordLibrary.setEnabled(false);
        btUpdateWordLibrary.setName("btUpdateWordLibrary"); // NOI18N
        btUpdateWordLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateWordLibraryActionPerformed(evt);
            }
        });
        jPanel1.add(btUpdateWordLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 540, 330));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btAddLessonLibrary.setText("Add Lesson");
        btAddLessonLibrary.setName("btAddLessonLibrary"); // NOI18N
        btAddLessonLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddLessonLibraryActionPerformed(evt);
            }
        });
        jPanel2.add(btAddLessonLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        jSpLesson.setName("jSpLesson"); // NOI18N

        tbLesson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbLesson.setName("tbLesson"); // NOI18N
        tbLesson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLessonMouseClicked(evt);
            }
        });
        jSpLesson.setViewportView(tbLesson);

        jScrollPane4.setViewportView(jSpLesson);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 270, 190));

        btDeleteLessonLibrary.setText("Delete Lesson");
        btDeleteLessonLibrary.setEnabled(false);
        btDeleteLessonLibrary.setName("btDeleteLessonLibrary"); // NOI18N
        btDeleteLessonLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteLessonLibraryActionPerformed(evt);
            }
        });
        jPanel2.add(btDeleteLessonLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 310, 270));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbImagePreviewLibrary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImagePreviewLibrary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/niImage.png"))); // NOI18N
        lbImagePreviewLibrary.setName("lbImagePreviewLibrary"); // NOI18N
        jPanel3.add(lbImagePreviewLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 290, 140));

        lbFuriganaLibrary.setFont(lbFuriganaLibrary.getFont().deriveFont(lbFuriganaLibrary.getFont().getSize()+7f));
        lbFuriganaLibrary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFuriganaLibrary.setText("にほんご");
        lbFuriganaLibrary.setName("lbFuriganaLibrary"); // NOI18N
        jPanel3.add(lbFuriganaLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 298, 50));

        lbMeaningPreviewLibrary.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbMeaningPreviewLibrary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMeaningPreviewLibrary.setText("Tiếng Nhật");
        lbMeaningPreviewLibrary.setName("lbMeaningPreviewLibrary"); // NOI18N
        jPanel3.add(lbMeaningPreviewLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 298, 50));

        lbKanjPreviewLibrary.setFont(lbKanjPreviewLibrary.getFont().deriveFont(lbKanjPreviewLibrary.getFont().getSize()+7f));
        lbKanjPreviewLibrary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbKanjPreviewLibrary.setText("日本語");
        lbKanjPreviewLibrary.setName("lbKanjPreviewLibrary"); // NOI18N
        jPanel3.add(lbKanjPreviewLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 298, 50));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 310, 310));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Kanji : ");
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setText("Furigana :");
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel4.setText("Meaning :");
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel5.setText("Image :");
        jLabel5.setName("jLabel5"); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        tfImageLibrary.setEditable(false);
        tfImageLibrary.setFocusable(false);
        tfImageLibrary.setName("tfImageLibrary"); // NOI18N
        jPanel4.add(tfImageLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 210, -1));

        btUpdateLibrary.setText("Update");
        btUpdateLibrary.setEnabled(false);
        btUpdateLibrary.setName("btUpdateLibrary"); // NOI18N
        btUpdateLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateLibraryActionPerformed(evt);
            }
        });
        jPanel4.add(btUpdateLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 70, 60));

        btBrowserImageLibrary.setText("Browse");
        btBrowserImageLibrary.setEnabled(false);
        btBrowserImageLibrary.setName("btBrowserImageLibrary"); // NOI18N
        btBrowserImageLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBrowserImageLibraryActionPerformed(evt);
            }
        });
        jPanel4.add(btBrowserImageLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        tfMeaningLibrary.setEditable(false);
        tfMeaningLibrary.setFocusable(false);
        tfMeaningLibrary.setName("tfMeaningLibrary"); // NOI18N
        tfMeaningLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMeaningLibraryActionPerformed(evt);
            }
        });
        jPanel4.add(tfMeaningLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 300, -1));

        tfFuriganaLibrary.setEditable(false);
        tfFuriganaLibrary.setFocusable(false);
        tfFuriganaLibrary.setName("tfFuriganaLibrary"); // NOI18N
        tfFuriganaLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFuriganaLibraryActionPerformed(evt);
            }
        });
        jPanel4.add(tfFuriganaLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 300, -1));

        tfKanjiLibrary.setEditable(false);
        tfKanjiLibrary.setFocusable(false);
        tfKanjiLibrary.setName("tfKanjiLibrary"); // NOI18N
        jPanel4.add(tfKanjiLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 300, -1));

        btSaveLibrary.setText("Save");
        btSaveLibrary.setEnabled(false);
        btSaveLibrary.setName("btSaveLibrary"); // NOI18N
        btSaveLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveLibraryActionPerformed(evt);
            }
        });
        jPanel4.add(btSaveLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 70, 60));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 540, 250));
    }// </editor-fold>//GEN-END:initComponents

    private void tfFuriganaLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFuriganaLibraryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFuriganaLibraryActionPerformed

    private void tfMeaningLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMeaningLibraryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMeaningLibraryActionPerformed

    private void tbWordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbWordMouseClicked
        // TODO add your handling code here:
        btUpdateWordLibrary.setEnabled(true);
        btSaveLibrary.setEnabled(false);
        btDeleteWordLibrary.setEnabled(true);

        if (tbLesson.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Please choose the lesson");
            return;
        }
        row = tbWord.getSelectedRow();
        word = new Word();
        selection(word, row);
        fillUpdate(word);
    }//GEN-LAST:event_tbWordMouseClicked
    private void tbLessonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLessonMouseClicked
        // TODO add your handling code here:
        enableButtons();
        if (tbLesson.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Please choose the lesson :-)");
            return;
        }
        row = tbLesson.getSelectedRow();
        lessonId = (Integer) tbLesson.getValueAt(row, 0);
        fillTbWord();
        //fillTbLesson();
    }//GEN-LAST:event_tbLessonMouseClicked

    private void btUpdateLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateLibraryActionPerformed
        // TODO add your handling code here:
        word.setKanji(tfKanjiLibrary.getText());
        word.setFurigana(tfFuriganaLibrary.getText());
        word.setMeaning(tfMeaningLibrary.getText());
        word.setImage(tfImageLibrary.getText());

        String result = WordInteraction.updateWord(word);

        fillTbLesson();
        fillTbWord();

        if (result.equals("Update successfully")) {
            JOptionPane.showMessageDialog(null, "Update successfully :D");
        }
    }//GEN-LAST:event_btUpdateLibraryActionPerformed

    private void btBrowserImageLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBrowserImageLibraryActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int action = fileChooser.showOpenDialog(this);
        if (action == JFileChooser.APPROVE_OPTION) {
            File f = fileChooser.getSelectedFile();
            tfImageLibrary.setText(f.getAbsolutePath());
        }
    }//GEN-LAST:event_btBrowserImageLibraryActionPerformed

    private void btNewLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewLibraryActionPerformed
        // TODO add your handling code here:
        btUpdateLibrary.setEnabled(false);
        btSaveLibrary.setEnabled(true);

        resetTextField();
    }//GEN-LAST:event_btNewLibraryActionPerformed

    private void btAddLessonLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddLessonLibraryActionPerformed
        // TODO add your handling code here:
        String newNameLesson = JOptionPane.showInputDialog("Enter name of lesson").trim();

        Lesson s = new Lesson(newNameLesson);
        if (newNameLesson.length() == 0) {
            JOptionPane.showMessageDialog(null, "Name you've inputed is invalid! :-(");
        } else {
            JOptionPane.showMessageDialog(null, LessonInteraction.insertLesson(s));
            fillTbLesson();
            row = tbLesson.getSelectedRow();
            lessonId = s.getLessonID();
            fillTbWord();
        }
    }//GEN-LAST:event_btAddLessonLibraryActionPerformed

    private void btDeleteLessonLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteLessonLibraryActionPerformed
        // TODO add your handling code here:
        int row = tbLesson.getSelectedRow();
        int lessonIdToDelete = (Integer) tbLesson.getValueAt(row, 0);
        int sureChoice = JOptionPane.showConfirmDialog(null, "Are you sure? :-o");

        if (sureChoice == 0) {
            WordInteraction.deleteWordByLessonId(lessonIdToDelete);
            JOptionPane.showMessageDialog(null, LessonInteraction.deleteLesson(lessonIdToDelete));
        }

        fillTbLesson();
        tbLesson.changeSelection(0, 1, false, false);
        lessonId = 0;
        fillTbWord();
    }//GEN-LAST:event_btDeleteLessonLibraryActionPerformed

    private void btSaveLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveLibraryActionPerformed
        // TODO add your handling code here:
        int selectedRowTbLesson = tbLesson.getSelectedRow();
        int rowToAdd = (Integer) tbLesson.getValueAt(tbLesson.getSelectedRow(), 0);

        //System.out.println(rowToAdd);
        Word wordToAdd = new Word();

        wordToAdd.setKanji(tfKanjiLibrary.getText());
        wordToAdd.setFurigana(tfFuriganaLibrary.getText());
        wordToAdd.setMeaning(tfMeaningLibrary.getText());
        wordToAdd.setImage(tfImageLibrary.getText());
        wordToAdd.setLessonID(rowToAdd);

        WordInteraction.insertWord(wordToAdd);

        fillTbLesson();
        fillTbWord();

        tbWord.clearSelection();
        tbWord.changeSelection(0, 1, false, false);

        tbLesson.changeSelection(selectedRowTbLesson, 1, false, false);
    }//GEN-LAST:event_btSaveLibraryActionPerformed

    private void btDeleteWordLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteWordLibraryActionPerformed
        // TODO add your handling code here:
        int selectedRowTbLesson = tbLesson.getSelectedRow();

        int rowWord = tbWord.getSelectedRow();
        int rowLesson = tbLesson.getSelectedRow();

        int wordIdToDelete = (Integer) tbWord.getValueAt(rowWord, 0);
        int sureChoice = JOptionPane.showConfirmDialog(null, "Are you sure? :-o");

        if (sureChoice == 0) {
            WordInteraction.deleteWordByWordId(wordIdToDelete);
        }

        tbWord.changeSelection(0, 1, false, false);
        tbLesson.changeSelection(rowLesson, lessonId, true, true);
        rowWord = tbWord.getSelectedRow();
        word = new Word();

        selection(word, rowWord);
        fillTbWord();
        fillTbLesson();

        tbLesson.changeSelection(selectedRowTbLesson, 1, false, false);
    }//GEN-LAST:event_btDeleteWordLibraryActionPerformed

    private void btUpdateWordLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateWordLibraryActionPerformed
        // TODO add your handling code here:
        btUpdateLibrary.setEnabled(true);
        setEditableFocusableTextFields();
    }//GEN-LAST:event_btUpdateWordLibraryActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddLessonLibrary;
    private javax.swing.JButton btBrowserImageLibrary;
    private javax.swing.JButton btDeleteLessonLibrary;
    private javax.swing.JButton btDeleteWordLibrary;
    private javax.swing.JButton btNewLibrary;
    private javax.swing.JButton btSaveLibrary;
    private javax.swing.JButton btUpdateLibrary;
    private javax.swing.JButton btUpdateWordLibrary;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jSpLesson;
    private javax.swing.JLabel lbFuriganaLibrary;
    private javax.swing.JLabel lbImagePreviewLibrary;
    private javax.swing.JLabel lbKanjPreviewLibrary;
    private javax.swing.JLabel lbMeaningPreviewLibrary;
    private javax.swing.JTable tbLesson;
    private javax.swing.JTable tbWord;
    private javax.swing.JTextField tfFuriganaLibrary;
    private javax.swing.JTextField tfImageLibrary;
    private javax.swing.JTextField tfKanjiLibrary;
    private javax.swing.JTextField tfMeaningLibrary;
    // End of variables declaration//GEN-END:variables
    private Word word = null;
    private int row = 0;
    private int lessonId = 0;

    public int selection(Word w, int r) {
        w.setKanji((String) tbWord.getValueAt(r, 1));
        w.setFurigana((String) tbWord.getValueAt(r, 2));
        w.setMeaning((String) tbWord.getValueAt(r, 3));
        w.setImage((String) tbWord.getValueAt(r, 4));
        w.setLessonID((Integer) tbWord.getValueAt(r, 5));

        return r;
    }

    public int selection(Lesson l, int r) {
        l.setLessonID((Integer) tbLesson.getValueAt(r, 0));
        l.setLessonName((String) tbLesson.getValueAt(r, 1));

        return r;
    }

    public void fillUpdate(Word word) {
        //Image
        String imagePath;
        imagePath = word.getImage();
        if (imagePath != null) {
            tfImageLibrary.setText(imagePath);
            lbImagePreviewLibrary.setIcon(new ImageIcon(word.getImage()));
        }
        //Kanji
        String kanji;
        kanji = word.getKanji();
        lbKanjPreviewLibrary.setText(kanji);
        tfKanjiLibrary.setText(kanji);
        //Furigana
        String furigana;
        furigana = word.getFurigana();
        lbFuriganaLibrary.setText(furigana);
        tfFuriganaLibrary.setText(furigana);
        //Meaning
        String meaning;
        meaning = word.getMeaning();
        lbMeaningPreviewLibrary.setText(meaning);
        tfMeaningLibrary.setText(meaning);
    }

    //Reset Update/Add Word Text Fields
    private void resetTextField() {

        setEditableFocusableTextFields();
        
        tfFuriganaLibrary.setText(null);
        tfImageLibrary.setText(null);
        tfKanjiLibrary.setText(null);
        tfMeaningLibrary.setText(null);
    }

    private void setEditableFocusableTextFields() {
        tfFuriganaLibrary.setFocusable(true);
        tfImageLibrary.setFocusable(true);
        tfKanjiLibrary.setFocusable(true);
        tfMeaningLibrary.setFocusable(true);

        tfFuriganaLibrary.setEditable(true);
        tfImageLibrary.setEditable(true);
        tfKanjiLibrary.setEditable(true);
        tfMeaningLibrary.setEditable(true);
    }

    private void enableButtons() {
        btBrowserImageLibrary.setEnabled(true);
        btDeleteLessonLibrary.setEnabled(true);
        btNewLibrary.setEnabled(true);
    }
}
