/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entity.User;
import Interaction.UserInteraction;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author Giang
 */
public class Mainmenu extends javax.swing.JFrame implements KeyListener {

    /**
     * Creates new form Mainmenu
     */
    //set size
    private Component frame;

    //Set bt background
    public void setButtonBg(JButton bt) {
        Color inActive = new Color(240, 240, 240);
        Color Active = new Color(53, 79, 113);

        btExit.setBackground(inActive);
        btGame.setBackground(inActive);
        btHelp.setBackground(inActive);
        btHome.setBackground(inActive);
        btLearn.setBackground(inActive);
        btLibrary.setBackground(inActive);
        bt.setBackground(Active);
    }

    public Mainmenu() {
        initComponents();
        btHome.addKeyListener(this);
        callJPanel(new StartPanel());
        UserFunction();
      //  st = LoginDialog.getNameUr();
        if (!"".equals(ur.getUserAvatar())) {
            ImageIcon icon = new ImageIcon(ur.getUserAvatar());
            Image scaleImage = icon.getImage().getScaledInstance(120, 120, Image.SCALE_DEFAULT);
            icon = new ImageIcon(scaleImage);
            lbAvatar.setIcon(icon);
        }
        lbAcc.setText("Hello " + ur.getUserName()+ "!");
       // setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplContent = new javax.swing.JPanel();
        jplMenu = new javax.swing.JPanel();
        jpSubmenu = new javax.swing.JPanel();
        btExit = new javax.swing.JButton();
        btHelp = new javax.swing.JButton();
        btGame = new javax.swing.JButton();
        btLearn = new javax.swing.JButton();
        btLibrary = new javax.swing.JButton();
        btHome = new javax.swing.JButton();
        lbAvatar = new javax.swing.JLabel();
        lbAcc = new javax.swing.JLabel();
        jplMain = new javax.swing.JPanel();
        jpHeader = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src/Images/header.png");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jpfooter = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jplContent.setBackground(new java.awt.Color(255, 255, 255));
        jplContent.setOpaque(false);
        jplContent.setPreferredSize(new java.awt.Dimension(660, 631));
        jplContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jplMenu.setBackground(new java.awt.Color(255, 255, 255));
        jplMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jplMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpSubmenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpSubmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        btExit.setText("Exit                 ");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });
        jpSubmenu.add(btExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 150, -1));

        btHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/help a.png"))); // NOI18N
        btHelp.setText("Help              ");
        btHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHelpActionPerformed(evt);
            }
        });
        jpSubmenu.add(btHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 150, -1));

        btGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/game.png"))); // NOI18N
        btGame.setText("Entertainment");
        btGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGameActionPerformed(evt);
            }
        });
        jpSubmenu.add(btGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 150, -1));

        btLearn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Let's_learn.png"))); // NOI18N
        btLearn.setText("Let's Learn  ");
        btLearn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLearnActionPerformed(evt);
            }
        });
        jpSubmenu.add(btLearn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 150, -1));

        btLibrary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/libraly.png"))); // NOI18N
        btLibrary.setText("Library       ");
        btLibrary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btLibraryMouseClicked(evt);
            }
        });
        btLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLibraryActionPerformed(evt);
            }
        });
        jpSubmenu.add(btLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 150, -1));

        btHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Home.png"))); // NOI18N
        btHome.setBorder(null);
        btHome.setBorderPainted(false);
        btHome.setContentAreaFilled(false);
        btHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btHomeMouseExited(evt);
            }
        });
        btHome.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btHomeMouseMoved(evt);
            }
        });
        btHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHomeActionPerformed(evt);
            }
        });
        jpSubmenu.add(btHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 100));

        jplMenu.add(jpSubmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 170, 410));

        lbAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon_Admin.png"))); // NOI18N
        jplMenu.add(lbAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 140));

        lbAcc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAcc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAcc.setText("name");
        jplMenu.add(lbAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 144, 170, 30));

        jplContent.add(jplMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 170, -1));

        jplMain.setBackground(new java.awt.Color(56, 79, 113));
        jplMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jplMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jplContent.add(jplMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 850, 590));

        javax.swing.GroupLayout jpHeaderLayout = new javax.swing.GroupLayout(jpHeader);
        jpHeader.setLayout(jpHeaderLayout);
        jpHeaderLayout.setHorizontalGroup(
            jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        jpHeaderLayout.setVerticalGroup(
            jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jplContent.add(jpHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 50));

        jpfooter = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src/Images/footer.png");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };

        javax.swing.GroupLayout jpfooterLayout = new javax.swing.GroupLayout(jpfooter);
        jpfooter.setLayout(jpfooterLayout);
        jpfooterLayout.setHorizontalGroup(
            jpfooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        jpfooterLayout.setVerticalGroup(
            jpfooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jplContent.add(jpfooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 1020, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplContent, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplContent, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// action event for EXIT menu item.
    // method to exit main frame

    private int exitFrame() {
        int n = JOptionPane.showConfirmDialog(frame, "Do you want to exit", "Yes or no?", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        return 1;
    }

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        // TODO add your handling code here:
        //exitFrame();
        System.exit(0);
    }//GEN-LAST:event_btExitActionPerformed

    private void btLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLibraryActionPerformed
        // TODO add your handling code here
        callJPanel(StartPanel.libraly);
        setButtonBg(btLibrary);
    }//GEN-LAST:event_btLibraryActionPerformed

    private void btLearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLearnActionPerformed
        // TODO add your handling code here:
        setButtonBg(btLearn);
        callJPanel(StartPanel.learn);
    }//GEN-LAST:event_btLearnActionPerformed

    private void btGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGameActionPerformed
        // TODO add your handling code here:
        setButtonBg(btGame);
        callJPanel(StartPanel.entertainment);

    }//GEN-LAST:event_btGameActionPerformed

    private void btHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHomeActionPerformed
        // TODO add your handling code here:
        setButtonBg(btHome);
        callJPanel(startPanel);

    }//GEN-LAST:event_btHomeActionPerformed

    private void btHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHelpActionPerformed
        // TODO add your handling code here:
        callJPanel(StartPanel.help);
        setButtonBg(btHelp);
    }//GEN-LAST:event_btHelpActionPerformed

    private void btHomeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHomeMouseMoved
        // TODO add your handling code here:
        btHome.setIcon(new ImageIcon("src\\Images\\Home focused.png"));
    }//GEN-LAST:event_btHomeMouseMoved

    private void btHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHomeMouseExited
        // TODO add your handling code here:
        btHome.setIcon(new ImageIcon("src\\Images\\Home.png"));
    }//GEN-LAST:event_btHomeMouseExited

    private void btLibraryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLibraryMouseClicked
        // TODO add your handling code here:
        setButtonBg(btLibrary);
    }//GEN-LAST:event_btLibraryMouseClicked
    public static void callJPanel(JPanel jpanel) {
        jplMain.removeAll();
        jpanel.setVisible(false);
        jplMain.add(jpanel, new AbsoluteConstraints(0, 0, jplMain.getWidth(), jplMain.getHeight()));
        jplMain.updateUI();
        jpanel.setVisible(true);
    }

     public void UserFunction (){
        ur= new User();
        ur.setUserName(LoginDialog.getNameUr());
        ur.setUserAvatar(LoginDialog.getAvatarPath());
        String mess = UserInteraction.insertUser(ur);
        //System.out.println(mess + ur.getUserName());
    }
    /**
     * @param args the command line arguments
     u*/
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Mainmenu.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(Mainmenu.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(Mainmenu.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Mainmenu.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                LoginDialog loginD = new LoginDialog(null, true);
               if (LoginDialog.getStatus()) {
                    Mainmenu cFrame = new Mainmenu();
                    cFrame.setLocationRelativeTo(null);
                    cFrame.setVisible(true);
                    cFrame.setButtonBg(cFrame.btHome);
                } else {
                    System.exit(0);
                }
                //new Mainmenu().setVisible(true);
            }
        });
    }
    private StartPanel startPanel = new StartPanel();
    public static User ur = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExit;
    private javax.swing.JButton btGame;
    private javax.swing.JButton btHelp;
    private javax.swing.JButton btHome;
    private javax.swing.JButton btLearn;
    private javax.swing.JButton btLibrary;
    private javax.swing.JPanel jpHeader;
    private javax.swing.JPanel jpSubmenu;
    private javax.swing.JPanel jpfooter;
    private javax.swing.JPanel jplContent;
    public static javax.swing.JPanel jplMain;
    private javax.swing.JPanel jplMenu;
    private javax.swing.JLabel lbAcc;
    private javax.swing.JLabel lbAvatar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
        // throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void keyPressed(KeyEvent e) {
        int keyCode = e.getKeyCode();
        if (e.isControlDown()) {


            if (keyCode == KeyEvent.VK_1) {
                callJPanel(StartPanel.learn);
            }
            if (keyCode == KeyEvent.VK_2) {
                callJPanel(StartPanel.entertainment);
            }
            if (keyCode == KeyEvent.VK_3) {
                callJPanel(StartPanel.test);
            }
            if (keyCode == KeyEvent.VK_5) {
                callJPanel(StartPanel.libraly);
            }
            if (keyCode == KeyEvent.VK_6) {
                callJPanel(StartPanel.help);
            }
            if (keyCode == KeyEvent.VK_7) {
                AboutUs aboutUsD = new AboutUs(null, true);
            }
            if (keyCode == KeyEvent.VK_H) {
                callJPanel(startPanel);
            }
            if (keyCode == KeyEvent.VK_X) {
                exitFrame();
            }
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }
}
