/*
 * StartPannel: Display the menu for the user to select
 */

/*
 * StartPanel.java
 *
 */
package GUI;

import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Duc
 */
public class StartPanel extends javax.swing.JPanel {


    /**
     * Creates new form StartPanel
     */
    public StartPanel() {
    
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblErin = new javax.swing.JLabel();
        pnlStartPnl = new javax.swing.JPanel();
        pnlLearn = new javax.swing.JPanel();
        lbLearn = new javax.swing.JLabel();
        detail_learn = new javax.swing.JLabel();
        btLearn = new javax.swing.JButton();
        pnlTest = new javax.swing.JPanel();
        btTest = new javax.swing.JButton();
        lbTest = new javax.swing.JLabel();
        detail_Test = new javax.swing.JLabel();
        pnlLibraly = new javax.swing.JPanel();
        btLibrary = new javax.swing.JButton();
        lbLibrary = new javax.swing.JLabel();
        detail_libraly = new javax.swing.JLabel();
        pnlGame = new javax.swing.JPanel();
        btEntertainment = new javax.swing.JButton();
        lbEntertainment = new javax.swing.JLabel();
        detail_Entertainment = new javax.swing.JLabel();
        pnlRating = new javax.swing.JPanel();
        btRating = new javax.swing.JButton();
        lbRating = new javax.swing.JLabel();
        detail_Rating = new javax.swing.JLabel();
        pnlHelp = new javax.swing.JPanel();
        btHelp = new javax.swing.JButton();
        lbHelp = new javax.swing.JLabel();
        detail_Help = new javax.swing.JLabel();
        pnlAbout = new javax.swing.JPanel();
        btAboutUs = new javax.swing.JButton();
        lbAbout = new javax.swing.JLabel();
        detail_about = new javax.swing.JLabel();

        setBackground(new java.awt.Color(56, 79, 113));
        setMinimumSize(new java.awt.Dimension(660, 550));
        setPreferredSize(new java.awt.Dimension(850, 590));
        setLayout(null);

        lblErin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chos.png"))); // NOI18N
        lblErin.setName("lblErin"); // NOI18N
        add(lblErin);
        lblErin.setBounds(620, 300, 230, 340);

        pnlStartPnl.setBackground(new java.awt.Color(56, 79, 113));
        pnlStartPnl.setName("pnlStartPnl"); // NOI18N
        pnlStartPnl.setLayout(new java.awt.GridLayout(3, 3));

        pnlLearn.setBackground(new java.awt.Color(56, 79, 113));
        pnlLearn.setName("pnlLearn"); // NOI18N
        pnlLearn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLearnMouseClicked(evt);
            }
        });

        lbLearn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lbLearn.setForeground(java.awt.Color.white);
        lbLearn.setText("Let's learn"); // NOI18N
        lbLearn.setName("lbLearn"); // NOI18N
        lbLearn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLearnMouseClicked(evt);
            }
        });

        detail_learn.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        detail_learn.setForeground(java.awt.Color.white);
        detail_learn.setText("<html>Learn new word<br>Press Ctrl + 1"); // NOI18N
        detail_learn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        detail_learn.setName("detail_learn"); // NOI18N
        detail_learn.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btLearn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Learn.png"))); // NOI18N
        btLearn.setBorder(null);
        btLearn.setContentAreaFilled(false);
        btLearn.setFocusable(false);
        btLearn.setName("btLearn"); // NOI18N
        btLearn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btLearnMouseExited(evt);
            }
        });
        btLearn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btLearnMouseMoved(evt);
            }
        });
        btLearn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLearnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pnlLearnLayout = new org.jdesktop.layout.GroupLayout(pnlLearn);
        pnlLearn.setLayout(pnlLearnLayout);
        pnlLearnLayout.setHorizontalGroup(
            pnlLearnLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlLearnLayout.createSequentialGroup()
                .addContainerGap()
                .add(btLearn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(pnlLearnLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(detail_learn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .add(lbLearn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(42, 42, 42))
        );
        pnlLearnLayout.setVerticalGroup(
            pnlLearnLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlLearnLayout.createSequentialGroup()
                .add(pnlLearnLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlLearnLayout.createSequentialGroup()
                        .add(45, 45, 45)
                        .add(lbLearn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(detail_learn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(pnlLearnLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(btLearn)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pnlStartPnl.add(pnlLearn);

        pnlTest.setBackground(new java.awt.Color(56, 79, 113));
        pnlTest.setName("pnlTest"); // NOI18N
        pnlTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTestMouseClicked(evt);
            }
        });

        btTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Test.png"))); // NOI18N
        btTest.setBorder(null);
        btTest.setContentAreaFilled(false);
        btTest.setFocusable(false);
        btTest.setName("btTest"); // NOI18N
        btTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btTestMouseExited(evt);
            }
        });
        btTest.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btTestMouseMoved(evt);
            }
        });
        btTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTestActionPerformed(evt);
            }
        });

        lbTest.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lbTest.setForeground(java.awt.Color.white);
        lbTest.setText("All Test");
        lbTest.setName("lbTest"); // NOI18N

        detail_Test.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        detail_Test.setForeground(java.awt.Color.white);
        detail_Test.setText("<html>Test Leson 1 to 10<br>Press Ctrl + 3"); // NOI18N
        detail_Test.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        detail_Test.setName("detail_Test"); // NOI18N
        detail_Test.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        org.jdesktop.layout.GroupLayout pnlTestLayout = new org.jdesktop.layout.GroupLayout(pnlTest);
        pnlTest.setLayout(pnlTestLayout);
        pnlTestLayout.setHorizontalGroup(
            pnlTestLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlTestLayout.createSequentialGroup()
                .addContainerGap()
                .add(btTest, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlTestLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(detail_Test, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .add(lbTest, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlTestLayout.setVerticalGroup(
            pnlTestLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlTestLayout.createSequentialGroup()
                .add(pnlTestLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlTestLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(btTest, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 132, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(pnlTestLayout.createSequentialGroup()
                        .add(41, 41, 41)
                        .add(lbTest, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(detail_Test, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pnlStartPnl.add(pnlTest);

        pnlLibraly.setBackground(new java.awt.Color(56, 79, 113));
        pnlLibraly.setName("pnlLibraly"); // NOI18N
        pnlLibraly.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLibralyMouseClicked(evt);
            }
        });

        btLibrary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Library.png"))); // NOI18N
        btLibrary.setBorder(null);
        btLibrary.setContentAreaFilled(false);
        btLibrary.setFocusable(false);
        btLibrary.setName("btLibrary"); // NOI18N
        btLibrary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btLibraryMouseExited(evt);
            }
        });
        btLibrary.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btLibraryMouseMoved(evt);
            }
        });
        btLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLibraryActionPerformed(evt);
            }
        });

        lbLibrary.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lbLibrary.setForeground(java.awt.Color.white);
        lbLibrary.setText("Library");
        lbLibrary.setName("lbLibrary"); // NOI18N

        detail_libraly.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        detail_libraly.setForeground(java.awt.Color.white);
        detail_libraly.setText("<html>Add/edit new word, data<br>Press Ctrl + 5"); // NOI18N
        detail_libraly.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        detail_libraly.setName("detail_libraly"); // NOI18N
        detail_libraly.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        org.jdesktop.layout.GroupLayout pnlLibralyLayout = new org.jdesktop.layout.GroupLayout(pnlLibraly);
        pnlLibraly.setLayout(pnlLibralyLayout);
        pnlLibralyLayout.setHorizontalGroup(
            pnlLibralyLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlLibralyLayout.createSequentialGroup()
                .add(15, 15, 15)
                .add(btLibrary)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(pnlLibralyLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(detail_libraly, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 135, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lbLibrary, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlLibralyLayout.setVerticalGroup(
            pnlLibralyLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlLibralyLayout.createSequentialGroup()
                .add(pnlLibralyLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlLibralyLayout.createSequentialGroup()
                        .add(41, 41, 41)
                        .add(lbLibrary, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(detail_libraly, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(pnlLibralyLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(btLibrary)))
                .add(0, 38, Short.MAX_VALUE))
        );

        pnlStartPnl.add(pnlLibraly);

        pnlGame.setBackground(new java.awt.Color(56, 79, 113));
        pnlGame.setName("pnlGame"); // NOI18N
        pnlGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlGameMouseClicked(evt);
            }
        });

        btEntertainment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Entertainment.png"))); // NOI18N
        btEntertainment.setBorder(null);
        btEntertainment.setContentAreaFilled(false);
        btEntertainment.setFocusable(false);
        btEntertainment.setName("btEntertainment"); // NOI18N
        btEntertainment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btEntertainmentMouseExited(evt);
            }
        });
        btEntertainment.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btEntertainmentMouseMoved(evt);
            }
        });
        btEntertainment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntertainmentActionPerformed(evt);
            }
        });

        lbEntertainment.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lbEntertainment.setForeground(java.awt.Color.white);
        lbEntertainment.setText("Entertainment");
        lbEntertainment.setName("lbEntertainment"); // NOI18N
        lbEntertainment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbEntertainmentMouseClicked(evt);
            }
        });

        detail_Entertainment.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        detail_Entertainment.setForeground(java.awt.Color.white);
        detail_Entertainment.setText("<html>Play game and music<br>Press Ctrl + 2"); // NOI18N
        detail_Entertainment.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        detail_Entertainment.setName("detail_Entertainment"); // NOI18N
        detail_Entertainment.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        org.jdesktop.layout.GroupLayout pnlGameLayout = new org.jdesktop.layout.GroupLayout(pnlGame);
        pnlGame.setLayout(pnlGameLayout);
        pnlGameLayout.setHorizontalGroup(
            pnlGameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlGameLayout.createSequentialGroup()
                .addContainerGap()
                .add(btEntertainment)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlGameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(detail_Entertainment, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lbEntertainment, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .add(28, 28, 28))
        );
        pnlGameLayout.setVerticalGroup(
            pnlGameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlGameLayout.createSequentialGroup()
                .add(pnlGameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlGameLayout.createSequentialGroup()
                        .add(48, 48, 48)
                        .add(lbEntertainment, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(detail_Entertainment, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(pnlGameLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(btEntertainment, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pnlStartPnl.add(pnlGame);

        pnlRating.setBackground(new java.awt.Color(56, 79, 113));
        pnlRating.setName("pnlRating"); // NOI18N
        pnlRating.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlRatingMouseClicked(evt);
            }
        });

        btRating.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rating.png"))); // NOI18N
        btRating.setBorder(null);
        btRating.setContentAreaFilled(false);
        btRating.setFocusable(false);
        btRating.setName("btRating"); // NOI18N
        btRating.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btRatingMouseExited(evt);
            }
        });
        btRating.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btRatingMouseMoved(evt);
            }
        });
        btRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRatingActionPerformed(evt);
            }
        });

        lbRating.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lbRating.setForeground(java.awt.Color.white);
        lbRating.setText("Rating");
        lbRating.setName("lbRating"); // NOI18N

        detail_Rating.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        detail_Rating.setForeground(java.awt.Color.white);
        detail_Rating.setText("<html>Review top10 in game<br> and test.<br>Press Ctrl + 4"); // NOI18N
        detail_Rating.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        detail_Rating.setName("detail_Rating"); // NOI18N
        detail_Rating.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        org.jdesktop.layout.GroupLayout pnlRatingLayout = new org.jdesktop.layout.GroupLayout(pnlRating);
        pnlRating.setLayout(pnlRatingLayout);
        pnlRatingLayout.setHorizontalGroup(
            pnlRatingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlRatingLayout.createSequentialGroup()
                .addContainerGap()
                .add(btRating, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 136, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(10, 10, 10)
                .add(pnlRatingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lbRating, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(detail_Rating, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRatingLayout.setVerticalGroup(
            pnlRatingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlRatingLayout.createSequentialGroup()
                .add(pnlRatingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlRatingLayout.createSequentialGroup()
                        .add(42, 42, 42)
                        .add(lbRating, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(detail_Rating, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(pnlRatingLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(btRating)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pnlStartPnl.add(pnlRating);

        pnlHelp.setBackground(new java.awt.Color(56, 79, 113));
        pnlHelp.setName("pnlHelp"); // NOI18N
        pnlHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlHelpMouseClicked(evt);
            }
        });

        btHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Help.png"))); // NOI18N
        btHelp.setBorder(null);
        btHelp.setContentAreaFilled(false);
        btHelp.setFocusable(false);
        btHelp.setName("btHelp"); // NOI18N
        btHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btHelpMouseExited(evt);
            }
        });
        btHelp.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btHelpMouseMoved(evt);
            }
        });
        btHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHelpActionPerformed(evt);
            }
        });

        lbHelp.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lbHelp.setForeground(java.awt.Color.white);
        lbHelp.setText("Help");
        lbHelp.setName("lbHelp"); // NOI18N

        detail_Help.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        detail_Help.setForeground(java.awt.Color.white);
        detail_Help.setText("<html>Choose to read tutorial<br>Press Ctrl + 6"); // NOI18N
        detail_Help.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        detail_Help.setName("detail_Help"); // NOI18N
        detail_Help.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        org.jdesktop.layout.GroupLayout pnlHelpLayout = new org.jdesktop.layout.GroupLayout(pnlHelp);
        pnlHelp.setLayout(pnlHelpLayout);
        pnlHelpLayout.setHorizontalGroup(
            pnlHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlHelpLayout.createSequentialGroup()
                .addContainerGap()
                .add(btHelp)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(detail_Help)
                    .add(lbHelp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlHelpLayout.setVerticalGroup(
            pnlHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlHelpLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlHelpLayout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(lbHelp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(detail_Help, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(btHelp))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pnlStartPnl.add(pnlHelp);

        pnlAbout.setBackground(new java.awt.Color(56, 79, 113));
        pnlAbout.setName("pnlAbout"); // NOI18N
        pnlAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAboutMouseClicked(evt);
            }
        });

        btAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/About.png"))); // NOI18N
        btAboutUs.setBorder(null);
        btAboutUs.setContentAreaFilled(false);
        btAboutUs.setFocusable(false);
        btAboutUs.setName("btAboutUs"); // NOI18N
        btAboutUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAboutUsMouseExited(evt);
            }
        });
        btAboutUs.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btAboutUsMouseMoved(evt);
            }
        });
        btAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAboutUsActionPerformed(evt);
            }
        });

        lbAbout.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lbAbout.setForeground(java.awt.Color.white);
        lbAbout.setText("About us");
        lbAbout.setName("lbAbout"); // NOI18N

        detail_about.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        detail_about.setForeground(java.awt.Color.white);
        detail_about.setText("<html>About team project.<br>Press Ctrl + 7"); // NOI18N
        detail_about.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        detail_about.setName("detail_about"); // NOI18N
        detail_about.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        org.jdesktop.layout.GroupLayout pnlAboutLayout = new org.jdesktop.layout.GroupLayout(pnlAbout);
        pnlAbout.setLayout(pnlAboutLayout);
        pnlAboutLayout.setHorizontalGroup(
            pnlAboutLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlAboutLayout.createSequentialGroup()
                .addContainerGap()
                .add(btAboutUs)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlAboutLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lbAbout, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(detail_about, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlAboutLayout.setVerticalGroup(
            pnlAboutLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlAboutLayout.createSequentialGroup()
                .add(41, 41, 41)
                .add(pnlAboutLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btAboutUs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pnlAboutLayout.createSequentialGroup()
                        .add(23, 23, 23)
                        .add(lbAbout, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(detail_about, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pnlStartPnl.add(pnlAbout);

        add(pnlStartPnl);
        pnlStartPnl.setBounds(0, 20, 850, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void lbLearnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLearnMouseClicked
    }//GEN-LAST:event_lbLearnMouseClicked

    private void btLearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLearnActionPerformed
        Mainmenu.callJPanel(learn);
    }//GEN-LAST:event_btLearnActionPerformed

    private void pnlLearnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLearnMouseClicked
    }//GEN-LAST:event_pnlLearnMouseClicked

    private void btEntertainmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntertainmentActionPerformed
        Mainmenu.callJPanel(entertainment);
    }//GEN-LAST:event_btEntertainmentActionPerformed

    private void lbEntertainmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEntertainmentMouseClicked
    }//GEN-LAST:event_lbEntertainmentMouseClicked

    private void pnlGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGameMouseClicked
    }//GEN-LAST:event_pnlGameMouseClicked

    private void btTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTestActionPerformed
        Mainmenu.callJPanel(test);
    }//GEN-LAST:event_btTestActionPerformed

    private void pnlTestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTestMouseClicked
    }//GEN-LAST:event_pnlTestMouseClicked

    private void pnlHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHelpMouseClicked
    }//GEN-LAST:event_pnlHelpMouseClicked

    private void btStatisticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStatisticActionPerformed
    }//GEN-LAST:event_btStatisticActionPerformed

    private void pnlRatingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRatingMouseClicked
    }//GEN-LAST:event_pnlRatingMouseClicked

    private void pnlAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAboutMouseClicked
    }//GEN-LAST:event_pnlAboutMouseClicked

    private void btLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLibraryActionPerformed
        // TODO add your handling code here:
        Mainmenu.callJPanel(libraly);
    }//GEN-LAST:event_btLibraryActionPerformed

    private void pnlLibralyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLibralyMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlLibralyMouseClicked

    private void btLearnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLearnMouseMoved
        // TODO add your handling code here:
        btLearn.setIcon(new ImageIcon("src\\Images\\learn focused.png"));
    }//GEN-LAST:event_btLearnMouseMoved

    private void btLearnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLearnMouseExited
        // TODO add your handling code here:
        btLearn.setIcon(new ImageIcon("src\\Images\\learn.png"));
    }//GEN-LAST:event_btLearnMouseExited

    private void btAboutUsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAboutUsMouseMoved
        // TODO add your handling code here:
        btAboutUs.setIcon(new ImageIcon("src\\Images\\About focused.png"));
    }//GEN-LAST:event_btAboutUsMouseMoved

    private void btAboutUsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAboutUsMouseExited
        // TODO add your handling code here:
        btAboutUs.setIcon(new ImageIcon("src\\Images\\About.png"));
    }//GEN-LAST:event_btAboutUsMouseExited

    private void btEntertainmentMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEntertainmentMouseMoved
        // TODO add your handling code here:
        btEntertainment.setIcon(new ImageIcon("src\\Images\\Entertainment focused.png"));
    }//GEN-LAST:event_btEntertainmentMouseMoved

    private void btEntertainmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEntertainmentMouseExited
        // TODO add your handling code here:
        btEntertainment.setIcon(new ImageIcon("src\\Images\\Entertainment.png"));
    }//GEN-LAST:event_btEntertainmentMouseExited

    private void btLibraryMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLibraryMouseMoved
        // TODO add your handling code here:
        btLibrary.setIcon(new ImageIcon("src\\Images\\Library focused.png"));
    }//GEN-LAST:event_btLibraryMouseMoved

    private void btLibraryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLibraryMouseExited
        // TODO add your handling code here:
        btLibrary.setIcon(new ImageIcon("src\\Images\\Library.png"));
    }//GEN-LAST:event_btLibraryMouseExited

    private void btTestMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTestMouseMoved
        // TODO add your handling code here:
        btTest.setIcon(new ImageIcon("src\\Images\\Test focused.png"));
    }//GEN-LAST:event_btTestMouseMoved

    private void btTestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTestMouseExited
        // TODO add your handling code here:
        btTest.setIcon(new ImageIcon("src\\Images\\Test.png"));
    }//GEN-LAST:event_btTestMouseExited

    private void btHelpMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHelpMouseMoved
        // TODO add your handling code here:
        btHelp.setIcon(new ImageIcon("src\\Images\\Help focused.png"));
    }//GEN-LAST:event_btHelpMouseMoved

    private void btHelpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHelpMouseExited
        // TODO add your handling code here:
        btHelp.setIcon(new ImageIcon("src\\Images\\Help.png"));
    }//GEN-LAST:event_btHelpMouseExited

    private void btStatisticMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btStatisticMouseMoved
       
    }//GEN-LAST:event_btStatisticMouseMoved

    private void btStatisticMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btStatisticMouseExited
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btStatisticMouseExited

    private void btRatingMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRatingMouseMoved
        // TODO add your handling code here:
        btRating.setIcon(new ImageIcon("src\\Images\\Rating focused.png"));
    }//GEN-LAST:event_btRatingMouseMoved

    private void btRatingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRatingMouseExited
        // TODO add your handling code here:
        btRating.setIcon(new ImageIcon("src\\Images\\Rating.png"));
    }//GEN-LAST:event_btRatingMouseExited

    private void btRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRatingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRatingActionPerformed

    private void btAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAboutUsActionPerformed
        // TODO add your handling code here:
        AboutUs aboutUsD = new AboutUs(null, true);
    }//GEN-LAST:event_btAboutUsActionPerformed

    private void btHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHelpActionPerformed
        // TODO add your handling code here:
        try 
        { 
            String path = new File("").getAbsolutePath() + "\\Help.chm"; 
            File file = new File(path); 
             
            if(file.exists()) 
            { 
                Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " + path); 
            } 
            else 
            { 
                throw new Exception("File \"Help.chm\" not found!"); 
            } 
        } 
        catch(Exception ex) 
        { 
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Notice", JOptionPane.OK_OPTION); 
        }
    }//GEN-LAST:event_btHelpActionPerformed
    public static Library libraly = new Library();
    public static Learn learn = new Learn();
    public static Entertainment entertainment = new Entertainment();
    public static Help help = new Help();
    public static Test test = new Test();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAboutUs;
    private javax.swing.JButton btEntertainment;
    private javax.swing.JButton btHelp;
    private javax.swing.JButton btLearn;
    private javax.swing.JButton btLibrary;
    private javax.swing.JButton btRating;
    private javax.swing.JButton btTest;
    private javax.swing.JLabel detail_Entertainment;
    private javax.swing.JLabel detail_Help;
    private javax.swing.JLabel detail_Rating;
    private javax.swing.JLabel detail_Test;
    private javax.swing.JLabel detail_about;
    private javax.swing.JLabel detail_learn;
    private javax.swing.JLabel detail_libraly;
    private javax.swing.JLabel lbAbout;
    private javax.swing.JLabel lbEntertainment;
    private javax.swing.JLabel lbHelp;
    private javax.swing.JLabel lbLearn;
    private javax.swing.JLabel lbLibrary;
    private javax.swing.JLabel lbRating;
    private javax.swing.JLabel lbTest;
    private javax.swing.JLabel lblErin;
    private javax.swing.JPanel pnlAbout;
    private javax.swing.JPanel pnlGame;
    private javax.swing.JPanel pnlHelp;
    private javax.swing.JPanel pnlLearn;
    private javax.swing.JPanel pnlLibraly;
    private javax.swing.JPanel pnlRating;
    private javax.swing.JPanel pnlStartPnl;
    private javax.swing.JPanel pnlTest;
    // End of variables declaration//GEN-END:variables
}
