/*
 * StartPannel: Display the menu for the user to select
 */

/*
 * StartPanel.java
 *
 */
package GUI;

import Interaction.Clock;
import Interaction.LessonInteraction;
import Interaction.TestInteraction;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author
 */
public class Test extends javax.swing.JPanel {

    /**
     * Creates new form StartPanel
     */
    private Clock cl = null;

    public Test() {
        initComponents();
        fillTbLesson();
        for (int i = 0; i < 100; i++) {
            arrChoice[i] = 0;
        }
    }

    private void fillTbLesson() {
        Vector title = new Vector();
        title.add("ID");
        title.add("Lesson Name");
        Vector lesson = LessonInteraction.readLesson();
        if (lesson.size() > 0) {
            tbLesson.setModel(new DefaultTableModel(lesson, title));
            tbLesson.getColumnModel().getColumn(1).setPreferredWidth(20);

            tbLesson.getColumn("ID").setWidth(0);
            tbLesson.getColumn("ID").setMinWidth(0);

        }
    }

    private void fillTbTest() {

        Vector title = new Vector();
        title.add("ID");
        title.add("Question");
        title.add("A");
        title.add("B");
        title.add("C");
        title.add("D");
        title.add("RA");
        title.add("Set");
        Vector test = TestInteraction.readTestBySetID(setID);
        if (test.size() > 0) {
            jTableTest.setModel(new DefaultTableModel(test, title));
            jTableTest.getColumnModel().getColumn(1).setPreferredWidth(20);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGrWord = new javax.swing.ButtonGroup();
        btGrChoice = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbCountQ = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bStart = new javax.swing.JButton();
        tfTimer = new javax.swing.JTextField();
        lbGet = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jSpLesson = new javax.swing.JScrollPane();
        tbLesson = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        bNext = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        tfA = new javax.swing.JTextField();
        tfB = new javax.swing.JTextField();
        tfC = new javax.swing.JTextField();
        tfD = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        taQ = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTest = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        bFinish = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setName("jPanel1"); // NOI18N

        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(660, 550));
        setPreferredSize(new java.awt.Dimension(850, 590));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Choose the leson: ");
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Question:");
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 80, 20));

        lbCountQ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCountQ.setText("0/0");
        lbCountQ.setName("lbCountQ"); // NOI18N
        jPanel4.add(lbCountQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 50, 20));

        jLabel11.setText("Time:");
        jLabel11.setName("jLabel11"); // NOI18N
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 50, 20));

        bStart.setText("Start");
        bStart.setName("bStart"); // NOI18N
        bStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStartActionPerformed(evt);
            }
        });
        jPanel4.add(bStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 110, 50));

        tfTimer.setEditable(false);
        tfTimer.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tfTimer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfTimer.setText("00:00");
        tfTimer.setName("tfTimer"); // NOI18N
        tfTimer.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfTimerCaretUpdate(evt);
            }
        });
        jPanel4.add(tfTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 90, -1));

        lbGet.setName("lbGet"); // NOI18N
        jPanel4.add(lbGet, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 60, 20));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 380, 90));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jSpLesson.setName("jSpLesson"); // NOI18N

        tbLesson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbLesson.setName("tbLesson"); // NOI18N
        tbLesson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLessonMouseClicked(evt);
            }
        });
        jSpLesson.setViewportView(tbLesson);

        jScrollPane1.setViewportView(jSpLesson);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 190, 110));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 150));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel6.setName("jPanel6"); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Answer");
        jLabel8.setName("jLabel8"); // NOI18N
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        bNext.setText("Next");
        bNext.setName("bNext"); // NOI18N
        bNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNextActionPerformed(evt);
            }
        });
        jPanel6.add(bNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 70, -1));

        btGrChoice.add(jRadioButton1);
        jRadioButton1.setText("A");
        jRadioButton1.setName("jRadioButton1"); // NOI18N
        jPanel6.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        btGrChoice.add(jRadioButton2);
        jRadioButton2.setText("B");
        jRadioButton2.setName("jRadioButton2"); // NOI18N
        jPanel6.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        btGrChoice.add(jRadioButton3);
        jRadioButton3.setText("C");
        jRadioButton3.setName("jRadioButton3"); // NOI18N
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        btGrChoice.add(jRadioButton4);
        jRadioButton4.setText("D");
        jRadioButton4.setName("jRadioButton4"); // NOI18N
        jPanel6.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 440));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel7.setName("jPanel7"); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfA.setEditable(false);
        tfA.setName("tfA"); // NOI18N
        jPanel7.add(tfA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 300, -1));

        tfB.setEditable(false);
        tfB.setName("tfB"); // NOI18N
        jPanel7.add(tfB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 300, -1));

        tfC.setEditable(false);
        tfC.setName("tfC"); // NOI18N
        tfC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCActionPerformed(evt);
            }
        });
        jPanel7.add(tfC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 300, -1));

        tfD.setEditable(false);
        tfD.setName("tfD"); // NOI18N
        jPanel7.add(tfD, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 300, -1));

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        taQ.setEditable(false);
        taQ.setColumns(20);
        taQ.setRows(5);
        taQ.setName("taQ"); // NOI18N
        jScrollPane3.setViewportView(taQ);

        jPanel7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 320, 50));

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTableTest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableTest.setName("jTableTest"); // NOI18N
        jScrollPane2.setViewportView(jTableTest);

        jScrollPane4.setViewportView(jScrollPane2);

        jPanel7.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 10, 0));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -20, 720, 380));

        jCheckBox1.setText("I want to finish");
        jCheckBox1.setName("jCheckBox1"); // NOI18N
        jPanel3.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        bFinish.setText("Finish");
        bFinish.setName("bFinish"); // NOI18N
        bFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFinishActionPerformed(evt);
            }
        });
        jPanel3.add(bFinish, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, -1, -1));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 850, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void tbLessonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLessonMouseClicked
        // TODO add your handling code here:
        int rown = tbLesson.getSelectedRow();
        setID = (Integer) tbLesson.getValueAt(rown, 0);
        //System.out.println((String) tbLesson.getValueAt(rown, 1));
        fillTbTest();
    }//GEN-LAST:event_tbLessonMouseClicked

    private void tfCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCActionPerformed
    int[] arrChoice = new int[100];
    private void bNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNextActionPerformed
        // TODO add your handling code here:

        //  mark();
        arrChoice[c++] = selectedAnswer();
        row++;
        if (row + 1 > jTableTest.getRowCount()) {
            lbCountQ.setText(jTableTest.getRowCount() + "/" + jTableTest.getRowCount());
            row = 0;
            c = 0;
            lbCountQ.setText(row + 1 + "/" + jTableTest.getRowCount());
        } else {
            lbCountQ.setText(row + 1 + "/" + jTableTest.getRowCount());
        }
       
        if (arrChoice[row] == 1) {
            jRadioButton1.setSelected(true);
        } else if (arrChoice[row] == 2) {
            jRadioButton2.setSelected(true);
        } else if (arrChoice[row] == 3) {
            jRadioButton3.setSelected(true);
        } else if (arrChoice[row] == 4) {
            jRadioButton4.setSelected(true);
        } else if (arrChoice[row] == 0) {
            btGrChoice.clearSelection();
        }
      
        taQ.setText((String) jTableTest.getValueAt(row, 1));
        tfA.setText((String) jTableTest.getValueAt(row, 2));
        tfB.setText((String) jTableTest.getValueAt(row, 3));
        tfC.setText((String) jTableTest.getValueAt(row, 4));
        tfD.setText((String) jTableTest.getValueAt(row, 5));
        // //System.out.println("mark = " + mark);
    }//GEN-LAST:event_bNextActionPerformed
    boolean b = true;
    private void bStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStartActionPerformed
        // TODO add your handling code here:

        cl = new Clock(tfTimer);
        cl.start();
        final int i = 0;
        Timer t = null;
        ActionListener action = new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (cl.getSecond() == 0) {
                    if (b == true) {
                        cl.stop();
//                        for (int i = 0; i < c; i++) {
//                            //System.out.println(arrChoice[i]);
//                        }
                        mark();
                        //System.out.println("mark: " + mark);
                        Result rs = new Result(null,true);
                        b = false;
                    }
                }
            }
        };

        t = new Timer(100, action);
        t.start();

        taQ.setText((String) jTableTest.getValueAt(row, 1));
        tfA.setText((String) jTableTest.getValueAt(row, 2));
        tfB.setText((String) jTableTest.getValueAt(row, 3));
        tfC.setText((String) jTableTest.getValueAt(row, 4));
        tfD.setText((String) jTableTest.getValueAt(row, 5));

        lbCountQ.setText("1/" + jTableTest.getRowCount());
        bStart.setEnabled(false);
        tbLesson.setEnabled(false);

    }//GEN-LAST:event_bStartActionPerformed

    private void bFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFinishActionPerformed
        // TODO add your handling code here:
        cl.stop();
        mark();
        Result rs = new Result(null, true);
        bFinish.setEnabled(false);
    }//GEN-LAST:event_bFinishActionPerformed

    private void tfTimerCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfTimerCaretUpdate
        // TODO add your handling code here:
        //if(tfTimer.getText().toString().equals("00:00"))
        //System.out.println(tfTimer.getText().toString());
    }//GEN-LAST:event_tfTimerCaretUpdate

    private int selectedAnswer() {

        if (jRadioButton1.isSelected()) {
            choice = 1;
        } else if (jRadioButton2.isSelected()) {
            choice = 2;
        } else if ((jRadioButton3).isSelected()) {
            choice = 3;
        } else if ((jRadioButton4).isSelected()) {
            choice = 4;
        } else {
            choice = 0;
        }
        //System.out.println("choice = " + choice);
        return choice;
    }

    private void mark() {
        for (int i = 0; i < jTableTest.getRowCount(); i++) {
            if (arrChoice[i] == jTableTest.getValueAt(i, 6)) {
                mark++;
            }
        }
    }
    
    public static int getMark(){
        return mark;
    }
    private static int mark = 0;
    private int setID = 0;
    private int row = 0;
    int choice = 0;
    int c = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bFinish;
    private javax.swing.JButton bNext;
    private javax.swing.JButton bStart;
    private javax.swing.ButtonGroup btGrChoice;
    private javax.swing.ButtonGroup btGrWord;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jSpLesson;
    private javax.swing.JTable jTableTest;
    private javax.swing.JLabel lbCountQ;
    private javax.swing.JLabel lbGet;
    private javax.swing.JTextArea taQ;
    private javax.swing.JTable tbLesson;
    private javax.swing.JTextField tfA;
    private javax.swing.JTextField tfB;
    private javax.swing.JTextField tfC;
    private javax.swing.JTextField tfD;
    private javax.swing.JTextField tfTimer;
    // End of variables declaration//GEN-END:variables
}
